store_t = "CREATE table IF NOT EXISTS  {{schema}}.store_t (ID BIGINT NOT NULL PRIMARY KEY, NAME VARCHAR(250) NOT NULL, LIVE_DATE TIMESTAMP NOT NULL, STATUS BOOL NOT NULL);"

customer_t = "CREATE table IF NOT EXISTS {{schema}}.customer_t (ID BIGINT NOT NULL PRIMARY KEY, NAME VARCHAR(250) NOT NULL, CITY VARCHAR NOT NULL, CREATE_DATE TIMESTAMP NOT NULL);"

sales_t = "CREATE table IF NOT EXISTS {{schema}}.sales_t (ID BIGINT NOT NULL PRIMARY KEY, CREATE_DATE TIMESTAMP NOT NULL, PAID_PRICE NUMERIC(10, 2) NOT NULL);"

sales_tx_t = "CREATE table IF NOT EXISTS {{schema}}.sales_tx_t (ID BIGINT NOT NULL PRIMARY KEY, STATUS BOOL NOT NULL, SALES_ID BIGINT REFERENCES {{schema}}.sales_t(ID), STORE_ID BIGINT REFERENCES {{schema}}.store_t(ID));"